---
### General Information ###
info:
  app:
    name: Autoscaler Scaling Engine Service Broker
    description: Autoscaler Core Service Broker for Cloud Foundry Service Deployments
    version: 1.2.0

spring:
  profiles: default
  ### General Information ###
  application:
      name: osb-autoscaler-scaling-engine
  ### Security ###
  ssl:
    acceptselfsigned: true
  ### Cloud Config ###
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8081}

server:
  port: ${SERVER_PORT:8080}

### Logging ###
logging:
  file: ${LOG_FILE:osb-autoscaler-core.log}
  level:
    root: ${LOG_LEVEL_ROOT:INFO}

